services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file: .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-network
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - postgres-network
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
